<a href="https://colab.research.google.com/github/Sandeepdora/AdaBoost/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#importing the Modules requires
import numpy as nn
import pandas as pp
from sklearn import tree as tt
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import r2_score as r2
from sklearn.metrics import mean_squared_error as mse
from sklearn.ensemble import AdaBoostRegressor as abc
from sklearn.ensemble import RandomForestRegressor as rfr

In [21]:
gg = pp.read_csv('diabetes.csv')  #reading the data set
gg.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
x = gg[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']] # I want all the first 7 columns to be the features
y = gg['Outcome']      #I need the last column as the feature

In [0]:
x_train, x_test, y_train, y_test = tts(x, y, test_size = 0.2, random_state = 2) #dividing the data into training and testing data and random_state = 2 and test_size is 0.2

In [44]:
#Since the data is full of numbers I used Regressor method
clf = tt.DecisionTreeRegressor()  #clf stands for Classifier and tt for tree 
clf.fit(x_train, y_train)  #fit the training and testing data

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [54]:
clf_pred = clf.predict(x_test) 
clf_pred

array([0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0.])

In [57]:
clf_r2 = r2(y_test, clf_pred)  #Took r_square error to find out the difference between them
clf_r2

-0.22446483180428123

In [58]:
clf_mse = mse(y_test, clf_pred)   #Also used Mean Squared Error to find the error
clf_mse

0.2532467532467532

In [40]:
abcclf = abc(n_estimators = 100, random_state= 0)    #abcclf stands for AdaBoostRegressor  and gave the n_estimator parameter to 100
abcclf.fit(x_train, y_train)  #Fitting training data into the classifier

AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=100, random_state=0)

In [59]:
abc_pred = abcclf.predict(x_test)    #predicting the results
abc_pred

array([0.23275862, 0.48051948, 0.36363636, 0.50625   , 0.51277014,
       0.31948882, 0.20710059, 0.52467532, 0.2601626 , 0.51277014,
       0.49622642, 0.51277014, 0.65789474, 0.39497717, 0.19444444,
       0.55311355, 0.52767528, 0.05851064, 0.51277014, 0.58088235,
       0.57323232, 0.58088235, 0.45905172, 0.48920863, 0.2195122 ,
       0.42924528, 0.49288256, 0.51497006, 0.48051948, 0.4795539 ,
       0.51277014, 0.51277014, 0.19827586, 0.42924528, 0.49622642,
       0.61940299, 0.49288256, 0.50625   , 0.51277014, 0.11764706,
       0.46666667, 0.27536232, 0.48051948, 0.45905172, 0.05851064,
       0.12871287, 0.46666667, 0.57323232, 0.325     , 0.51497006,
       0.60674157, 0.50442478, 0.50625   , 0.51497006, 0.52467532,
       0.52158273, 0.58088235, 0.52551985, 0.53738318, 0.05851064,
       0.51497006, 0.58585859, 0.57323232, 0.57246377, 0.48051948,
       0.47368421, 0.58088235, 0.31948882, 0.46666667, 0.50625   ,
       0.31818182, 0.27536232, 0.48920863, 0.45905172, 0.26016

In [60]:
abc_r2 = r2(y_test, abc_pred)   #using r_square error I found the error between the test and the prediction
abc_r2

0.07601246518661575

In [61]:
abc_mse = mse(y_test, abc_pred) #using Mean Squared error I found the error between the test and the prediction
abc_mse

0.191101318024104

In [48]:
rfrclf = rfr(n_estimators = 100, max_depth = 10)  #rfrclf stands for RandomForestRegressor and gave the n_estimators parameter to 100
rfrclf.fit(x_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=10, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [63]:
rfr_pred = rfrclf.predict(x_test)   #predicting the results 
rfr_pred

array([1.65060728e-02, 3.35738149e-01, 5.68155966e-02, 4.81031207e-01,
       5.17567997e-01, 4.87314439e-02, 5.06072783e-04, 7.80000000e-01,
       7.76539142e-02, 4.05575049e-01, 6.87037037e-02, 6.77025397e-01,
       7.49687500e-01, 9.25165816e-02, 0.00000000e+00, 8.84575136e-01,
       7.01821429e-01, 0.00000000e+00, 4.59252276e-01, 9.47980769e-01,
       8.41673804e-01, 8.04867430e-01, 4.38126724e-02, 4.87500000e-01,
       1.00000000e-02, 7.70924629e-02, 6.67121212e-01, 3.76597801e-01,
       3.88454003e-01, 3.43035357e-01, 5.20661875e-01, 4.38004369e-01,
       0.00000000e+00, 1.42301184e-01, 3.30000000e-01, 9.15230769e-01,
       4.02646994e-01, 6.89175354e-01, 4.80975098e-01, 6.00000000e-02,
       2.63560046e-01, 1.12753036e-02, 2.56994858e-01, 8.75207841e-02,
       0.00000000e+00, 0.00000000e+00, 2.67590830e-01, 4.69223258e-01,
       1.96062500e-01, 3.86251526e-01, 5.30000000e-01, 3.86847664e-01,
       6.54725161e-01, 6.97767101e-01, 6.67600674e-01, 6.47479586e-01,
      

In [69]:
rfr_r2 = r2(y_test, rfr_pred) #r2 error for finding out the error
rfr_r2

0.20998722258785563

In [66]:
rfr_mse = mse(y_test, rfr_pred)   #Mean Squared Error for Error finding
rfr_mse

0.16339233737588837

In [74]:
ans = pp.Series([['Method', 'r2 error', 'mse'], ['Decision Tree',round(clf_r2, 6), round(clf_mse, 6)], ['AdaBoost', round(abc_r2, 6), round(abc_mse, 6)], ['RandomForest', round(rfr_r2, 6), round(rfr_mse, 6)]])
ans   #Creating a pandas DataFrame to show the erros in one view

0                 [Method, r2 error, mse]
1    [Decision Tree, -0.224465, 0.253247]
2          [AdaBoost, 0.076012, 0.191101]
3      [RandomForest, 0.209987, 0.163392]
dtype: object

From the above errors of different Methods I conclude that **AdaBoostRegressor**  is the best way among the other 2 models